services:
  db:
    build:
      context: ./sqlserver/
      dockerfile: Dockerfile
    image: sqlserver
    container_name: sqlserver-db
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Abc123!ab
      - MSSQL_PID=Express
      - MSSQL_LCID=1041
      - MSSQL_COLLATION=Japanese_CI_AS
      - TZ=Asia/Tokyo
      - DB_NAME=example
    volumes:
      - ./sqlserver/init:/docker-entrypoint-initdb.d
    restart: always
