services:
  db:
    build:
      context: ./mariadb/
      dockerfile: Dockerfile
    image: mariadb
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hoge
      MYSQL_DATABASE: exmaple
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_pass
      TZ: Asia/Tokyo
    volumes:
      - ./mariadb/init:/docker-entrypoint-initdb.d
    restart: always

