services:
  app:
    container_name: app
    image: anglar-image
    build:
      context: ./{project-name}
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
