services:
  dotnet:
    container_name: dotnet-container
    build:
      context: ./ProjectName
      dockerfile: Dockerfile
    image: dotnet-image
    environment:
      - TZ=Asia/Tokyo
    restart: always
